version: '3.8'

services:
  server:
    build: ./server
    env_file:
      - ./server/.env
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=8080
      - URI=mongodb://database:27017/TestDatabase
    ports:
      - 8080:8080
    networks:
      - node-network

  database:
    image: mongo:7.0.2
    logging:
      driver: none
    ports:
      - 27017:27017
    volumes:
      - NdeysKitchen:/data/db
    networks:
      - node-network

  client:
    build: ./client
    environment:
      - PORT=8081
    env_file:
      - ./client/.env.development.local
    networks:
      - node-network
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8081:8081
volumes:
  NdeysKitchen:

networks:
  node-network:
    driver: bridge
